// Maps icon name strings from page definitions to lucide-react components.
// Curated subset of finance-relevant icons to keep bundle size reasonable.

import {
  Wallet,
  Banknote,
  Coins,
  CreditCard,
  PiggyBank,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  LineChart,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Store,
  Home,
  Car,
  Utensils,
  Coffee,
  HeartPulse,
  Plane,
  Gift,
  Calendar,
  Clock,
  Target,
  Flag,
  AlertTriangle,
  CheckCircle,
  Info,
  Zap,
  Scale,
  Building2,
  Landmark,
  Calculator,
  Percent,
  Hash,
  Layers,
  LayoutDashboard,
  FileText,
  List,
  Grid3x3,
  ArrowLeftRight,
  ArrowUpDown,
  Repeat,
  Split,
  Merge,
} from "lucide-react";

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "bar-chart-3": BarChart3,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  receipt: Receipt,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  store: Store,
  home: Home,
  car: Car,
  utensils: Utensils,
  coffee: Coffee,
  "heart-pulse": HeartPulse,
  plane: Plane,
  gift: Gift,
  calendar: Calendar,
  clock: Clock,
  target: Target,
  flag: Flag,
  "alert-triangle": AlertTriangle,
  "check-circle": CheckCircle,
  info: Info,
  zap: Zap,
  scale: Scale,
  "building-2": Building2,
  landmark: Landmark,
  calculator: Calculator,
  percent: Percent,
  hash: Hash,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "file-text": FileText,
  list: List,
  "grid-3x3": Grid3x3,
  "arrow-left-right": ArrowLeftRight,
  "arrow-up-down": ArrowUpDown,
  repeat: Repeat,
  split: Split,
  merge: Merge,
};

export function getIcon(name: string): React.ComponentType<{ className?: string }> {
  return ICON_MAP[name] || FileText;
}
