/**
 * Reads plugin/ directory and generates src/cli/plugin-files.ts
 * with all file contents embedded as string constants.
 *
 * Run: bun scripts/generate-plugin-embed.ts
 * Run before: bun build --compile
 */

import { readdirSync, readFileSync, statSync } from "fs";
import { join, relative } from "path";

const PLUGIN_DIR = join(import.meta.dir, "..", "plugin");
const OUT_FILE = join(import.meta.dir, "..", "src", "cli", "plugin-files.ts");

interface ToolFiles {
  [relativePath: string]: string;
}

interface PluginBundle {
  [tool: string]: ToolFiles;
}

function collectFiles(dir: string, base: string): [string, string][] {
  const results: [string, string][] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full).replace(/\\/g, "/");
    if (statSync(full).isDirectory()) {
      results.push(...collectFiles(full, base));
    } else {
      results.push([rel, readFileSync(full, "utf-8")]);
    }
  }
  return results;
}

// Collect files per tool integration
const bundle: PluginBundle = {};

// Claude Code — the canonical plugin (agents, skills, hooks, scripts, CONTEXT.md, plugin.json)
const claudeFiles: ToolFiles = {};
const claudeDirs = ["agents", "skills", "hooks", "scripts", ".claude-plugin"];
for (const dir of claudeDirs) {
  const dirPath = join(PLUGIN_DIR, dir);
  try {
    for (const [rel, content] of collectFiles(dirPath, PLUGIN_DIR)) {
      claudeFiles[rel] = content;
    }
  } catch {
    // dir may not exist
  }
}
// Add CONTEXT.md
try {
  claudeFiles["CONTEXT.md"] = readFileSync(join(PLUGIN_DIR, "CONTEXT.md"), "utf-8");
} catch {}
bundle["claude-code"] = claudeFiles;

// Other tools — from integrations/
const integrationsDir = join(PLUGIN_DIR, "integrations");
try {
  for (const tool of readdirSync(integrationsDir)) {
    const toolDir = join(integrationsDir, tool);
    if (!statSync(toolDir).isDirectory()) continue;
    const files: ToolFiles = {};
    for (const [rel, content] of collectFiles(toolDir, toolDir)) {
      files[rel] = content;
    }
    bundle[tool] = files;
  }
} catch {}

// Generate TypeScript
const lines: string[] = [
  "// AUTO-GENERATED by scripts/generate-plugin-embed.ts — do not edit",
  "// Embeds plugin files so they survive bun build --compile.",
  "",
  "export interface PluginBundle {",
  "  [tool: string]: { [path: string]: string };",
  "}",
  "",
  "export const PLUGIN_FILES: PluginBundle = {",
];

for (const [tool, files] of Object.entries(bundle)) {
  lines.push(`  ${JSON.stringify(tool)}: {`);
  for (const [path, content] of Object.entries(files)) {
    lines.push(`    ${JSON.stringify(path)}: ${JSON.stringify(content)},`);
  }
  lines.push("  },");
}

lines.push("};");
lines.push("");

await Bun.write(OUT_FILE, lines.join("\n"));

const toolCount = Object.keys(bundle).length;
const fileCount = Object.values(bundle).reduce((sum, files) => sum + Object.keys(files).length, 0);
console.log(`Generated ${OUT_FILE}`);
console.log(`  ${toolCount} tools, ${fileCount} files embedded`);
